### Get all categories
GET http://localhost:8080/api/categories
Accept: application/json

### Get category by id
GET http://localhost:8080/api/categories/7
Accept: application/json

### Create new category
POST http://localhost:8080/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "shoes"
}

### Update category by id
PUT http://localhost:8080/api/categories/7
Accept: application/json
Content-Type: application/json

{
  "name": "hats"
}

### Delete category by id
DELETE http://localhost:8080/api/categories/7
Accept: application/json